name: Branch

on:
  push:
    branches-ignore:
      - master

env:
  LOG_LEVELS: fatal
  TLS_UNPROTECTED: world

jobs:
  Cancel-Old-Runs:
    runs-on: ubuntu-latest

    steps:
      - uses: rokroskar/workflow-run-cleanup-action@master
        env:
          GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"

  Test-Linux:
    runs-on: ubuntu-18.04

    steps:
      - uses: actions/checkout@v2

      - name: Use latest LTS Node.js
        uses: actions/setup-node@v1
        with:
          node-version: lts/*
          registry-url: https://npm.pkg.github.com/
          scope: "@sealsystems"

      - name: Get Node.js version
        run: echo "NODE_VERSION=$(node --version)" >> $GITHUB_ENV

      - name: Cache Node.js modules
        uses: actions/cache@v1
        env:
          cache-name: cache-node-modules
        with:
          # npm cache files are stored in `~/.npm` on Linux/macOS
          path: ~/.npm
          key: ${{ runner.os }}-${{ env.cache-name }}-${{ env.NODE_VERSION }}-${{ hashFiles('**/package-lock.json') }}

      - name: Install dependencies
        run: npm ci
        env:
          # Use personal access token, must be set for *each step*
          NODE_AUTH_TOKEN: ${{secrets.CI_TOKEN}}

      - name: Run tests
        run: npm run bot
        env:
          # Use personal access token, must be set for *each step*
          NODE_AUTH_TOKEN: ${{secrets.CI_TOKEN}}

  Test-Windows:
    runs-on: windows-2019

    steps:
      - uses: actions/checkout@v2

      - name: Use latest LTS Node.js
        uses: actions/setup-node@v1
        with:
          node-version: lts/*
          registry-url: https://npm.pkg.github.com/
          scope: "@sealsystems"

      - name: Install dependencies
        run: npm ci
        env:
          # Use personal access token, must be set for *each step*
          NODE_AUTH_TOKEN: ${{secrets.CI_TOKEN}}

      - name: Run tests
        run: npm run bot
        env:
          # Use personal access token, must be set for *each step*
          NODE_AUTH_TOKEN: ${{secrets.CI_TOKEN}}
