name: Master

on:
  push:
    branches:
      - master
      - "[0-9].[0-9].x"

env:
  LOG_LEVELS: fatal
  TLS_UNPROTECTED: world

jobs:
  Test-Linux:
    # Ignore release commits
    if: "!startsWith(github.event.head_commit.message, 'Release')"

    runs-on: ubuntu-18.04

    steps:
      - uses: actions/checkout@v2

      - name: Use Node.js 12.13.1
        uses: actions/setup-node@v1
        with:
          node-version: 12.13.1
          registry-url: https://npm.pkg.github.com/
          scope: "@sealsystems"

      - name: Cache Node.js modules
        uses: actions/cache@v1
        env:
          cache-name: cache-node-modules
        with:
          # npm cache files are stored in `~/.npm` on Linux/macOS
          path: ~/.npm
          key: ${{ runner.os }}-${{ env.cache-name }}-12.13.1-${{ hashFiles('**/package-lock.json') }}

      - name: Install dependencies
        run: npm ci
        env:
          # Use personal access token, must be set for *each step*
          NODE_AUTH_TOKEN: ${{secrets.CI_TOKEN}}

      - name: Run tests
        run: npm run bot
        env:
          # Use personal access token, must be set for *each step*
          NODE_AUTH_TOKEN: ${{secrets.CI_TOKEN}}

  Test-Windows:
    # Ignore release commits
    if: "!startsWith(github.event.head_commit.message, 'Release')"

    runs-on: windows-2019

    steps:
      - uses: actions/checkout@v2

      - name: Use Node.js 12.13.1
        uses: actions/setup-node@v1
        with:
          node-version: 12.13.1
          registry-url: https://npm.pkg.github.com/
          scope: "@sealsystems"

      - name: Install dependencies
        run: npm ci
        env:
          # Use personal access token, must be set for *each step*
          NODE_AUTH_TOKEN: ${{secrets.CI_TOKEN}}

      - name: Run tests
        run: npm run bot
        env:
          # Use personal access token, must be set for *each step*
          NODE_AUTH_TOKEN: ${{secrets.CI_TOKEN}}

  Release:
    # Ignore release commits
    if: "!startsWith(github.event.head_commit.message, 'Release')"

    needs:
      - Test-Linux
      - Test-Windows

    runs-on: ubuntu-18.04

    env:
      GIT_AUTHOR_EMAIL: com.git@sealsystems.de
      GIT_AUTHOR_NAME: CI Build
      GIT_COMMITTER_EMAIL: com.git@sealsystems.de
      GIT_COMMITTER_NAME: CI Build
      # Use personal access token for creating releases on GitHub
      GITHUB_TOKEN: ${{ secrets.CI_TOKEN }}
      # Use personal access token for publishing on GitHub Packages
      NPM_TOKEN: ${{ secrets.CI_TOKEN }}

    steps:
      - uses: actions/checkout@v2
        with:
          # Use personal access token for cloning (and later pushing) code
          token: ${{ secrets.CI_TOKEN }}

      - name: Use Node.js 12.13.1
        uses: actions/setup-node@v1
        with:
          node-version: 12.13.1
          registry-url: https://npm.pkg.github.com/
          scope: "@sealsystems"

      - name: Cache Node.js modules
        uses: actions/cache@v1
        env:
          cache-name: cache-node-modules
        with:
          # npm cache files are stored in `~/.npm` on Linux/macOS
          path: ~/.npm
          key: ${{ runner.os }}-${{ env.cache-name }}-12.13.1-${{ hashFiles('**/package-lock.json') }}

      - name: Install dependencies
        run: npm ci
        env:
          # Use personal access token, must be set for *each step*
          NODE_AUTH_TOKEN: ${{secrets.CI_TOKEN}}

      - name: "Bugfix release: Set distribution tag accordingly to not remove 'latest' tag from the current version"
        # Only on bugfix branches
        if: github.ref != 'refs/heads/master'
        run: |
          echo "Patching package.json ..."
          sed -i 's|"registry": "https://npm.pkg.github.com"|"registry": "https://npm.pkg.github.com", "tag": "bugfix"|' package.json

      - name: Trigger release
        run: npm run release
        env:
          # Use personal access token, must be set for *each step*
          NODE_AUTH_TOKEN: ${{secrets.CI_TOKEN}}
