name: Nightly

on:
  schedule:
    - cron: "30 2 * * *"

jobs:
  Update-Build-Configuration:
    runs-on: ubuntu-18.04

    steps:
      - uses: actions/checkout@v2

      - name: Use Node.js 12.13.1
        uses: actions/setup-node@v1
        with:
          node-version: 12.13.1
          registry-url: https://npm.pkg.github.com/
          scope: "@sealsystems"

      - name: Cache Node.js modules
        uses: actions/cache@v1
        env:
          cache-name: cache-node-modules
        with:
          # npm cache files are stored in `~/.npm` on Linux/macOS
          path: ~/.npm
          key: ${{ runner.os }}-${{ env.cache-name }}-12.13.1-${{ hashFiles('**/package-lock.json') }}

      - name: Install dependencies
        run: npm i
        env:
          # Use personal access token, must be set for *each step*
          NODE_AUTH_TOKEN: ${{ secrets.CI_TOKEN }}

      - name: Install yeoman
        #run: npm install --no-save --force yo generator-seal-node
        run: |
          # Workaround as long as generator-seal-node in not available on GitHub Packages
          export GIT_HTTP_EXTRAHEADER=$(git config --get http.https://github.com/.extraheader)
          git config --unset http.https://github.com/.extraheader
          npm i -g yo git+https://${{ secrets.CI_TOKEN }}:x-oauth-basic@github.com/plossys/generator-seal-node.git
          git config --add http.https://github.com/.extraheader "${GIT_HTTP_EXTRAHEADER}"
        env:
          # Use personal access token, must be set for *each step*
          NODE_AUTH_TOKEN: ${{ secrets.CI_TOKEN }}

      - name: Update build config
        run: npx yo seal-node:oss-module --force
        env:
          # Use personal access token, must be set for *each step*
          NODE_AUTH_TOKEN: ${{ secrets.CI_TOKEN }}

      - name: Create pull request
        uses: peter-evans/create-pull-request@v2
        with:
          title: Update build configuration
          body: |
            The build configuration of this project is outdated and may no longer work.
            This pull request will be merged automatically if there are no conflicts.
          branch: nightly/update-build-configuration
          commit-message: Update build configuration
          committer: CI Build <com.git@sealsystems.de>
          author: CI Build <com.git@sealsystems.de>
          reviewers: 
          team-reviewers: com-infrastructure
          token: ${{ secrets.CI_TOKEN }}
