name: Publish on npmjs.org

on:
  release:
    types: [published]

jobs:
  Publish:
    runs-on: ubuntu-18.04

    steps:
      - uses: actions/checkout@v2

      - name: Use latest LTS Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 14.17.6
          registry-url: https://npm.pkg.github.com/
          scope: "@sealsystems"

      - name: Get Node.js version
        run: echo "NODE_VERSION=$(node --version)" >> $GITHUB_ENV

      - name: Cache Node.js modules
        uses: actions/cache@v1
        env:
          cache-name: cache-node-modules
        with:
          # npm cache files are stored in `~/.npm` on Linux/macOS
          path: ~/.npm
          key: ${{ runner.os }}-${{ env.cache-name }}-${{ env.NODE_VERSION }}-${{ hashFiles('**/package-lock.json') }}

      - name: Install dependencies
        run: npm ci
        env:
          # Use personal access token, must be set for *each step*
          NODE_AUTH_TOKEN: ${{secrets.CI_TOKEN}}

      - name: Publish on npmjs.org
        run: |
          echo "Patching package.json ..."
          sed -i 's|"registry": "https://npm.pkg.github.com"|"registry": "https://registry.npmjs.org"|' package.json

          echo "Patching .npmrc ..."
          echo "@sealsystems:registry=https://registry.npmjs.org" > .npmrc
          echo "//registry.npmjs.org/:_authToken=${NPM_TOKEN}" >> .npmrc

          echo "Publishing..."
          npm publish
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
