name: test

on:
  push:
    branches:
      - "**"
      - "!master"
      - "![0-9]+.[0-9]+.x"

env:
  LOG_LEVELS: fatal
  TLS_UNPROTECTED: world

jobs:
  Test-Linux:
    runs-on: ubuntu-22.04

    steps:
    - uses: actions/checkout@v4

    - name: Use Node.js 22.14.0
      uses: actions/setup-node@v4
      with:
        node-version: 22.14.0
        registry-url: https://npm.pkg.github.com/
        scope: "@sealsystems"

    - name: Cache Node.js modules
      uses: actions/cache@v4
      env:
        cache-name: cache-node-modules
      with:
        path: ~/.npm
        key: ${{ runner.os }}-${{ env.cache-name }}-22.14.0-${{ hashFiles('**/package-lock.json') }}

    - name: Install dependencies
      run: npm ci
      env:
        NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Run tests
      run: npm run bot
      env:
        NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

